### ISSUE TITLE
profile upload doesn't register

### ISSUE THREAD

**Issue by prgoncalves** [bhagdave/Beatcrumb-web#23]
Once I select a profile pic there is no image to upload in the 'upload file image' field.

**Comment by bhagdave** [comment]
This seems to be an HTML5 issue. There is none of our code behind the selection of files and it is all browser driven so I am not able to find a solution at the moment.

**Comment by bhagdave** [comment]
This was not an HTML5 issue but a problem with the dashboard event for the MP3 file upload and the image upload getting crossed.
