### ISSUE TITLE
Playback for Tracks from the search page is not working 

### ISSUE THREAD

**Issue by prgoncalves** [bhagdave/Beatcrumb-web#52]

**Comment by prgoncalves** [comment]
The playback issue seems to be intermittent. Currently the transfer of the crumbs is working fine but there is still no playback...
U: pprg
P: test2

**Comment by prgoncalves** [comment]
After clearing the cache playback started to work again. The remaining issues in the user flow is that the play crumb is still active, meaning that you can replay the song over and over again multiple times...

**Comment by bhagdave** [comment]
Could you please confirm what login details you were using in order that I can double check what is going wrong on this.

Thanks

**Comment by prgoncalves** [comment]
Hi Dave,

Yes, my login is U: pprg P: test2. 

*Note: I'm fairly new to Github I've been trying to find my way around the platform and have just been pressing buttons to see what each one does. I believe I 'forked' you; I apologize if that was a bad thing, I don't even know what it means quite honestly and I googled it and still I'm unclear...

**Comment by Rourkesta** [comment]
Dave, tracks are playing ok for me on the discover page and the crumb refill 
/share appears to be working but I am noticing that when I use the search bar on the discover page to find a track then play from that screen it opens up a new page and "nah ah" is written top left. screenshot below

![image](https://cloud.githubusercontent.com/assets/15316308/10746941/fe56d2d6-7c25-11e5-9151-38a7ee32c3d1.png)

**Comment by bhagdave** [comment]
So this is an issue in the search bar playing and not the discover page

**Comment by Rourkesta** [comment]
For me yes, I am able to play tracks or at least that one soundmatch track on the discover home page. When I attempt to click on a specific genre. The track will play but immediately redirect back to discover home page instead of leaving me on that screen to complete the crumb share process.

**Comment by bhagdave** [comment]
Yes that should be fixed with Issue #53 being fixed ealier today.  No matter what I do I am not able to emulate the problem you have so I am afraid I can not fix it.  The issue I have is different which I have put in a new issue.

**Comment by bhagdave** [comment]
I have just emulated the Nah ah page turning up.  I got it when I had played the same track three times (recorded as a bug elsewhere) and then clicked on a non-highlighted crumb to try an dplay that. It took me directly to the nah ah page.

**Comment by bhagdave** [comment]
This should now be fixed
