### ISSUE TITLE
Discover by Genre track plays but redirects 

### ISSUE THREAD

**Issue by Rourkesta** [bhagdave/Beatcrumb-web#53]
Track plays but immediately redirects user to main discover page with list of all discoverable tracks. 
U: Rourkesta
P: test
This may not be a top priority issue but I did want to bring it to your attention in case you were not already aware.

**Comment by bhagdave** [comment]
This should now be fixed.

**Comment by bhagdave** [comment]
I was just doing some testing and found this was still an issue. So if I select a Genre and then play a track, it will start to play the track and then go back to the Discover page with no genre set,

**Comment by bhagdave** [comment]
I have changed the session on the server so that they do not expire. This may or may not resolve this particular issue.

**Comment by bhagdave** [comment]
This is fixed with the recent changes.
