### ISSUE TITLE
Playing tracks on discover does not refresh track list

### ISSUE THREAD

**Issue by bhagdave** [bhagdave/Beatcrumb-web#64]

**Comment by bhagdave** [comment]
This looks like a race condition because the database underneath is correct.

**Comment by Rourkesta** [comment]
Is that a simple fix?

**Comment by bhagdave** [comment]
Probably not. It is caused because the server is still downloading the track when the client side asks for a new list. I suppose I could record that the user can not play the track before sending it to them.

**Comment by bhagdave** [comment]
This is an intermittent error which would certainly suggest a race condition

**Comment by bhagdave** [comment]
I tried this tonight and it seemed to be working fine. Will therefore close.
